### ISSUE TITLE
Entering Gid crashes with SegFault

### ISSUE THREAD

**Issue by mooneroid** [dcripplinger/rotj#24]
When I try to enter Gid from gid_perimeter, the game crashes with a segmentation fault, and this error message: `Fatal Python error: (pygame parachute) Segmentation Fault
./rotj.sh: line 2:  1127 Aborted                 (core dumped) ./src/rotj.py $1 $2 $3`.  No more details than that yet.

**Comment by dcripplinger** [comment]
Fixed
